http:
  routers:
    livechat:
      rule: Host(`livechat.localhost`)
      entryPoints:
        - web
      service: livechat

  services:
    livechat:
      loadBalancer:
        servers:
          - url: http://livechat-multitenant:3010
